#!/bin/bash
# Copyright 2025 Rodericus Ifo Krista
# SPDX-License-Identifier: MIT

set -e

psql -v ON_ERROR_STOP=1 -U ${POSTGRES_USER} <<-EOSQL
    CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD '${POSTGRES_REPLICATOR_PASSWORD}' CONNECTION LIMIT 5;
EOSQL